### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
added more description

### CODE REVIEW

**Comment by rasmusolle** [comment]
yes

**Comment by yeah-its-gloria** [comment]
Thanks!

**Comment by dakrk** [comment]
it isn't used for connecting to the shop's servers. from what i've found out, it's mainly used for getting device some device info (and maybe downloading titles)

**Comment by dhtdht020** [comment]
Read darky's. Didn't point that out as I'm not sure of most of it's uses.

**Comment by dakrk** [comment]
apart from that, good stuff 👍

**Comment by yeah-its-gloria** [comment]
Okay, feel free to make it the best README.md. :D

**Pull request merged**
